In [65]:
import numpy as np

In [66]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#Slicing the array
print(a[4:])
print(a[1:])
print(a[:1])
print(a[1:8:])

[ 5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[1]
[2 3 4 5 6 7 8]


In [68]:
#Change in arrays
a[0] = 10
print(a[0])

b = a[4:8]
b[2] = 1
a

10


array([10,  2,  3,  4,  5,  6,  1,  8,  9, 10])

In [69]:
#Two or more dimensions
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
print(a[1,3])
print(a[0,1])
print(a[2,2])

8
2
11


In [71]:
#Changes in 2dmin arrays, changes whole row
a[1]=123
a

array([[  1,   2,   3,   4],
       [123, 123, 123, 123],
       [  9,  10,  11,  12]])

In [72]:
a[1:, 2:]= 2
a

array([[  1,   2,   3,   4],
       [123, 123,   2,   2],
       [  9,  10,   2,   2]])

In [73]:
# --------------------
# 1D Slicing Examples
# --------------------
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Original 1D array:")
print(x)

print("\n1D slicing examples:")
print("Every 2nd element from start x[::2]     →", x[::2])
print("Every 2nd element from index 1 x[1::2]    →", x[1::2])
print("Reverse array x[::-1]    →", x[::-1])
print("Elements from index 2 to 6, step 2 x[2:7:2]   →", x[2:7:2])

# --------------------
# 2D Slicing Examples
# --------------------
a = np.arange(36).reshape(6, 6)
print("\nOriginal 2D array:")
print(a)

print("\n2D slicing examples:")
print("a[::2, ::2] → Even rows & columns:")
print(a[::2, ::2])

print("\na[1::2, ::2] → Odd rows & even columns:")
print(a[1::2, ::2])

print("\na[::-1, ::-1] → Full reversed matrix:")
print(a[::-1, ::-1])

Original 1D array:
[10 20 30 40 50 60 70 80]

1D slicing examples:
Every 2nd element from start x[::2]     → [10 30 50 70]
Every 2nd element from index 1 x[1::2]    → [20 40 60 80]
Reverse array x[::-1]    → [80 70 60 50 40 30 20 10]
Elements from index 2 to 6, step 2 x[2:7:2]   → [30 50 70]

Original 2D array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

2D slicing examples:
a[::2, ::2] → Even rows & columns:
[[ 0  2  4]
 [12 14 16]
 [24 26 28]]

a[1::2, ::2] → Odd rows & even columns:
[[ 6  8 10]
 [18 20 22]
 [30 32 34]]

a[::-1, ::-1] → Full reversed matrix:
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [74]:
print(np.zeros(5))
print(np.zeros((2,2)))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [75]:
print(np.ones(5))
print(np.ones((2,2)))

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [76]:
#Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [77]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[9]

9

In [79]:
slice_of_array = arr[4:7]
slice_of_array

array([4, 5, 6])

In [80]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99])

In [81]:
arr

array([ 0,  1,  2,  3, 99, 99, 99,  7,  8,  9, 10])

In [82]:
arr_copy = arr.copy()
slice_of_array[:] = 98
print(arr_copy)
print(arr)

[ 0  1  2  3 99 99 99  7  8  9 10]
[ 0  1  2  3 98 98 98  7  8  9 10]


In [87]:
arr = np.arange(50).reshape(10,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [88]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [89]:
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [94]:
import numpy as np

arr = np.arange(-5, 6)
print("Array:", arr)

print("\n--- Mathematical functions ---")
print("sqrt     :", np.sqrt(np.abs(arr)))      # square root (abs to avoid negatives)
print("square   :", np.square(arr))            # square
print("power^3  :", np.power(arr, 3))          # cube
print("abs      :", np.abs(arr))               # absolute value
print("sign     :", np.sign(arr))              # sign (-1, 0, +1)

print("\n--- Exponentials & logs ---")
print("exp      :", np.exp(arr))               # e^x
print("expm1    :", np.expm1(arr))             # e^x - 1
print("log      :", np.log(np.where(arr>0, arr, np.nan)))     # ln(x), safe
print("log10    :", np.log10(np.where(arr>0, arr, np.nan)))   # base-10 log
print("log2     :", np.log2(np.where(arr>0, arr, np.nan)))    # base-2 log

Array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]

--- Mathematical functions ---
sqrt     : [2.23606798 2.         1.73205081 1.41421356 1.         0.
 1.         1.41421356 1.73205081 2.         2.23606798]
square   : [25 16  9  4  1  0  1  4  9 16 25]
power^3  : [-125  -64  -27   -8   -1    0    1    8   27   64  125]
abs      : [5 4 3 2 1 0 1 2 3 4 5]
sign     : [-1 -1 -1 -1 -1  0  1  1  1  1  1]

--- Exponentials & logs ---
exp      : [6.73794700e-03 1.83156389e-02 4.97870684e-02 1.35335283e-01
 3.67879441e-01 1.00000000e+00 2.71828183e+00 7.38905610e+00
 2.00855369e+01 5.45981500e+01 1.48413159e+02]
expm1    : [ -0.99326205  -0.98168436  -0.95021293  -0.86466472  -0.63212056
   0.           1.71828183   6.3890561   19.08553692  53.59815003
 147.4131591 ]
log      : [       nan        nan        nan        nan        nan        nan
 0.         0.69314718 1.09861229 1.38629436 1.60943791]
log10    : [       nan        nan        nan        nan        nan        nan
 0.         0.30103    0

In [96]:
print("\n--- Trigonometric functions ---")
print("sin      :", np.sin(arr))               # sine
print("cos      :", np.cos(arr))               # cosine
print("tan      :", np.tan(arr))               # tangent
print("arcsin   :", np.arcsin(np.clip(arr/5, -1, 1)))  # inverse sine
print("arccos   :", np.arccos(np.clip(arr/5, -1, 1)))  # inverse cosine
print("arctan   :", np.arctan(arr))            # inverse tangent
print("deg2rad  :", np.deg2rad(arr))           # degrees → radians
print("rad2deg  :", np.rad2deg(arr))           # radians → degrees


--- Trigonometric functions ---
sin      : [ 0.95892427  0.7568025  -0.14112001 -0.90929743 -0.84147098  0.
  0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos      : [ 0.28366219 -0.65364362 -0.9899925  -0.41614684  0.54030231  1.
  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan      : [ 3.38051501 -1.15782128  0.14254654  2.18503986 -1.55740772  0.
  1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
arcsin   : [-1.57079633 -0.92729522 -0.64350111 -0.41151685 -0.20135792  0.
  0.20135792  0.41151685  0.64350111  0.92729522  1.57079633]
arccos   : [3.14159265 2.49809154 2.21429744 1.98231317 1.77215425 1.57079633
 1.36943841 1.15927948 0.92729522 0.64350111 0.        ]
arctan   : [-1.37340077 -1.32581766 -1.24904577 -1.10714872 -0.78539816  0.
  0.78539816  1.10714872  1.24904577  1.32581766  1.37340077]
deg2rad  : [-0.08726646 -0.06981317 -0.05235988 -0.03490659 -0.01745329  0.
  0.01745329  0.03490659  0.05235988  0.06981317  0.08726646]
rad2

In [97]:
print("\n--- Rounding functions ---")
print("round    :", np.round(arr/2.5))         # round to nearest
print("floor    :", np.floor(arr/2.5))         # round down
print("ceil     :", np.ceil(arr/2.5))          # round up
print("trunc    :", np.trunc(arr/2.5))         # truncate towards 0

print("\n--- Statistics & aggregates ---")
print("sum      :", np.sum(arr))               # sum
print("mean     :", np.mean(arr))              # average
print("median   :", np.median(arr))            # median
print("std      :", np.std(arr))               # standard deviation
print("var      :", np.var(arr))               # variance
print("min      :", np.min(arr))               # min
print("max      :", np.max(arr))               # max
print("cumsum   :", np.cumsum(arr))            # cumulative sum
print("cumprod  :", np.cumprod(arr))           # cumulative product
print("prod     :", np.prod(arr))              # product of all elements

print("\n--- Array utilities ---")
print("unique   :", np.unique(arr))            # unique values
print("sort     :", np.sort(arr[::-1]))        # sorted
print("clip     :", np.clip(arr, -2, 2))       # keep within [-2, 2]


--- Rounding functions ---
round    : [-2. -2. -1. -1. -0.  0.  0.  1.  1.  2.  2.]
floor    : [-2. -2. -2. -1. -1.  0.  0.  0.  1.  1.  2.]
ceil     : [-2. -1. -1. -0. -0.  0.  1.  1.  2.  2.  2.]
trunc    : [-2. -1. -1. -0. -0.  0.  0.  0.  1.  1.  2.]

--- Statistics & aggregates ---
sum      : 0
mean     : 0.0
median   : 0.0
std      : 3.1622776601683795
var      : 10.0
min      : -5
max      : 5
cumsum   : [ -5  -9 -12 -14 -15 -15 -14 -12  -9  -5   0]
cumprod  : [  -5   20  -60  120 -120    0    0    0    0    0    0]
prod     : 0

--- Array utilities ---
unique   : [-5 -4 -3 -2 -1  0  1  2  3  4  5]
sort     : [-5 -4 -3 -2 -1  0  1  2  3  4  5]
clip     : [-2 -2 -2 -2 -1  0  1  2  2  2  2]
