In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Slicing the array
print(a[4:])
print(a[1:])
print(a[:1])
print(a[1:8:])

[ 5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[1]
[2 3 4 5 6 7 8]


In [5]:
#Change in arrays
a[0] = 10
print(a[0])

b = a[4:8]
b[2] = 1
a

10


array([10,  2,  3,  4,  5,  6,  1,  8,  9, 10])

In [6]:
#Two or more dimensions
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
print(a[1,3])
print(a[0,1])
print(a[2,2])

8
2
11


In [8]:
#Changes in 2dmin arrays, changes whole row
a[1]=123
a

array([[  1,   2,   3,   4],
       [123, 123, 123, 123],
       [  9,  10,  11,  12]])

In [9]:
a[1:, 2:]= 2
a

array([[  1,   2,   3,   4],
       [123, 123,   2,   2],
       [  9,  10,   2,   2]])

In [10]:
# --------------------
# 1D Slicing Examples
# --------------------
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Original 1D array:")
print(x)

print("\n1D slicing examples:")
print("Every 2nd element from start x[::2]     →", x[::2])
print("Every 2nd element from index 1 x[1::2]    →", x[1::2])
print("Reverse array x[::-1]    →", x[::-1])
print("Elements from index 2 to 6, step 2 x[2:7:2]   →", x[2:7:2])

# --------------------
# 2D Slicing Examples
# --------------------
a = np.arange(36).reshape(6, 6)
print("\nOriginal 2D array:")
print(a)

print("\n2D slicing examples:")
print("a[::2, ::2] → Even rows & columns:")
print(a[::2, ::2])

print("\na[1::2, ::2] → Odd rows & even columns:")
print(a[1::2, ::2])

print("\na[::-1, ::-1] → Full reversed matrix:")
print(a[::-1, ::-1])

Original 1D array:
[10 20 30 40 50 60 70 80]

1D slicing examples:
Every 2nd element from start x[::2]     → [10 30 50 70]
Every 2nd element from index 1 x[1::2]    → [20 40 60 80]
Reverse array x[::-1]    → [80 70 60 50 40 30 20 10]
Elements from index 2 to 6, step 2 x[2:7:2]   → [30 50 70]

Original 2D array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

2D slicing examples:
a[::2, ::2] → Even rows & columns:
[[ 0  2  4]
 [12 14 16]
 [24 26 28]]

a[1::2, ::2] → Odd rows & even columns:
[[ 6  8 10]
 [18 20 22]
 [30 32 34]]

a[::-1, ::-1] → Full reversed matrix:
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [17]:
print(np.zeros(5))
print(np.zeros((2,2)))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [18]:
print(np.ones(5))
print(np.ones((2,2)))

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [20]:
#Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])