1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.23.5
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
Supported SIMD extensions i

3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [4]:
print(x.size)

10


5. How to get the documentation of the numpy add function from the command line?

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
x = np.zeros(10)
x[4] = 1 
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
x = np.flip(x)
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
x = np.matrix([[0,1,2], [3,4,5], [6,7,8]])
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
x = np.array([1,2,0,0,4,0])
np.where(x == 0)[0]

array([2, 3, 5])

11. Create a 3x3 identity matrix (★☆☆)

In [11]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
x = np.random.random((3,3,3))
x

array([[[0.3884315 , 0.33152682, 0.24450777],
        [0.90590353, 0.03030023, 0.75192111],
        [0.08436289, 0.99276781, 0.42377365]],

       [[0.32598954, 0.3550882 , 0.95996181],
        [0.5568785 , 0.20992995, 0.6617301 ],
        [0.06167572, 0.32560198, 0.52975745]],

       [[0.77185668, 0.37537459, 0.86817715],
        [0.34088047, 0.04946338, 0.89123963],
        [0.45482358, 0.46546014, 0.32286756]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
x = np.random.random((10,10))
print(x.max())
print(x.min())

0.9990867306478396
0.012699142005597519


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
x = np.random.random(30)
print(x.mean())

0.5532925948874482


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
x = np.ones((5,5))
x

x[1:-1, 1:-1] = 0 
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

https://numpy.org/doc/stable/reference/generated/numpy.pad.html

In [16]:
y = np.pad(array=x, pad_width=1)
y

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

https://numpy.org/doc/stable/reference/generated/numpy.diag.html

In [18]:
x = np.diag([1,2,3,4], k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
x = np.ones((8,8))
x

x[1::2, ::2] = 0
x[::2, 1::2] = 0
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
x = np.array([[1,0], [0,1]])
x = np.tile(x,(4,4))
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
x = np.random.rand(5,5)
x = (x-x.min() / (x.max() - x.min()))
x

array([[ 0.5170985 ,  0.77758761,  0.12938829,  0.19528111,  0.91166773],
       [ 0.29448892,  0.5903199 ,  0.70271615,  0.38274224,  0.72873551],
       [ 0.93808891,  0.92267946,  0.67534893,  0.49986266,  0.46609152],
       [ 0.12937523,  0.1701798 ,  0.12017291,  0.72451575,  0.11481043],
       [ 0.22120144, -0.00157218,  0.52431594,  0.22423845,  0.90758968]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([('r', np.uint8),
                   ('g', np.uint8),
                   ('b', np.uint8),
                   ('a', np.uint8)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)
z = np.matmul(x,y)
z

array([[0.12158407, 0.56316069],
       [0.40711005, 0.98834193],
       [0.47206822, 1.10127639],
       [0.37583674, 0.63369818],
       [0.26411137, 0.54462981]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
y = x[3:8]*-1
x[3:8] = y
x

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

In [26]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

x[(x >= 3) & (x <= 8)] *= -1
x

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

26. What is the output of the following script? (★☆☆)

https://stackoverflow.com/questions/57567658/why-sum-behaves-differently-after-i-import-numpy

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [28]:
Z = np.arange(10)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


28. What are the result of the following expressions? (★☆☆)

In [29]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_19131/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_19131/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([0.])

29. How to round away from zero a float array ? (★☆☆)

https://numpy.org/doc/2.2/reference/generated/numpy.floor.html

https://numpy.org/doc/2.2/reference/generated/numpy.ceil.html

In [30]:
#Floor
x = np.linspace(0,10, 15)
print(x)
x = np.floor(x)
print(x)
print('\n')
#Ceil
y = np.linspace(0,10,15)
print(y)
y = np.ceil(y)
print(y)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[ 0.  0.  1.  2.  2.  3.  4.  5.  5.  6.  7.  7.  8.  9. 10.]


[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[ 0.  1.  2.  3.  3.  4.  5.  5.  6.  7.  8.  8.  9. 10. 10.]


30. How to find common values between two arrays? (★☆☆)

In [31]:
x = np.array([1,2,3,4,5,6,7])
y = np.array([2,4,6,8,9])

print(np.intersect1d(x,y))

#For more than two arrayes use
from functools import reduce
z = np.array([3,6,9])
reduce(np.intersect1d,(x,y,z))

[2 4 6]


array([6])

31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
#np.seterr(all='ignore')

32. Is the following expressions true? (★☆☆)

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_19131/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(f'Yesterda was {yesterday}, today is {today}, tomrrow will be {tomorrow}')

Yesterda was 2025-06-15, today is 2025-06-16, tomrrow will be 2025-06-17


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

https://numpy.org/doc/2.2/reference/arrays.datetime.html

In [35]:
x = np.arange('2016-07-01', '2016-07-31', dtype = 'datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
x = np.ones(3) * 2
y = np.ones(3) * 3

x /= -2
y += x
y *= x
print(y)

[-2. -2. -2.]


36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
x = np.random.uniform(0,10,6)

print(x)

#1
print(x.astype(uint8))

#2
print(np.floor(x))

#3
print(np.trunc(x))

#4
print(np.round(x))

[8.36757162 8.83378213 9.20679275 4.87548255 4.83727362 2.21417707]
[8 8 9 4 4 2]
[8. 8. 9. 4. 4. 2.]
[8. 8. 9. 4. 4. 2.]
[8. 9. 9. 5. 5. 2.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
x = np.array([0,1,2,3,4])
y = np.tile(x,(5,1))
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def gen_array():
    for _ in range(10):
        yield np.random.randint(0, 100)
        
x = np.fromiter(gen_array(), dtype='int')
x


array([94, 99, 61, 61, 45, 68, 44, 67, 18, 47])

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
x = np.linspace(0,1,12)
x = x[1:11]
x.size

10

40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
np.sort(x)
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
x = np.arange(10)
x

#Sum
print(np.sum(x))

#Alternative
print(np.add.reduce(x))

45
45


42. Consider two random arrays A and B, check if they are equal (★★☆)

In [43]:
x = np.arange(10)
y = np.arange(10)

x == y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

43. Make an array immutable (read-only) (★★☆)

In [44]:
x = np.array(10)
x.flags.writeable = False
#x[0] = 1

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [47]:
cart_matrix = np.random.random([10,2])
x = cart_matrix[:, 0]
y = cart_matrix[:, 1]

r = np.sqrt(x**2, y**2)
theta = np.arctan(y, x)

polar = np.stack((r, theta), axis=1)

print("Cartesian Coordinates:\n", cart_matrix)
print("\nPolar Coordinates (r, theta):\n", polar)

Cartesian Coordinates:
 [[0.2028422  0.20567074]
 [0.53104671 0.58732392]
 [0.53934887 0.59854487]
 [0.32851449 0.34086591]
 [0.70443195 0.84989302]
 [0.5358879  0.59385369]
 [0.73397324 0.90209842]
 [0.01727204 0.01727375]
 [0.51653673 0.56797229]
 [0.34384511 0.35806904]]

Polar Coordinates (r, theta):
 [[0.92988903 0.2028422 ]
 [0.33506345 0.53104671]
 [0.89876257 0.53934887]
 [0.71664235 0.32851449]
 [0.67346965 0.70443195]
 [0.10736457 0.5358879 ]
 [0.94132341 0.73397324]
 [0.94575477 0.01727204]
 [0.08792763 0.51653673]
 [0.61534913 0.34384511]]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [61]:
x = np.random.rand(10)
print(f'Size of vector: {x.size}')

print(f'The max value is placed on: {x.argmax()}')
print(f'Its value is: {x.max()}')

x[9] = 0
#or
#x[x.argmax()] = 0
x

Size of vector: 10
The max value is placed on: 1
Its value is: 0.8932080702041404


array([0.51462288, 0.89320807, 0.85937285, 0.60683349, 0.01600969,
       0.27470017, 0.34674801, 0.42942794, 0.11320305, 0.        ])

46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [62]:
n = 10

x = np.linspace(0, 1, n)
y = np.linspace(0, 1, n)

xx, yy = np.meshgrid(x, y)

structured = np.zeros(n*n, dtype=[('x', float), ('y', float)])
structured['x'] = xx.ravel()
structured['y'] = yy.ravel()

print(structured)

[(0.        , 0.        ) (0.11111111, 0.        )
 (0.22222222, 0.        ) (0.33333333, 0.        )
 (0.44444444, 0.        ) (0.55555556, 0.        )
 (0.66666667, 0.        ) (0.77777778, 0.        )
 (0.88888889, 0.        ) (1.        , 0.        )
 (0.        , 0.11111111) (0.11111111, 0.11111111)
 (0.22222222, 0.11111111) (0.33333333, 0.11111111)
 (0.44444444, 0.11111111) (0.55555556, 0.11111111)
 (0.66666667, 0.11111111) (0.77777778, 0.11111111)
 (0.88888889, 0.11111111) (1.        , 0.11111111)
 (0.        , 0.22222222) (0.11111111, 0.22222222)
 (0.22222222, 0.22222222) (0.33333333, 0.22222222)
 (0.44444444, 0.22222222) (0.55555556, 0.22222222)
 (0.66666667, 0.22222222) (0.77777778, 0.22222222)
 (0.88888889, 0.22222222) (1.        , 0.22222222)
 (0.        , 0.33333333) (0.11111111, 0.33333333)
 (0.22222222, 0.33333333) (0.33333333, 0.33333333)
 (0.44444444, 0.33333333) (0.55555556, 0.33333333)
 (0.66666667, 0.33333333) (0.77777778, 0.33333333)
 (0.88888889, 0.33333333) (1.  

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [70]:
x = np.random.rand(5)
y = np.random.rand(5)

c = 1/ (x[:, None]) - (y[None, :])
print(f'{x}')
print(f'{y}')
c

[0.67929759 0.4256649  0.27875555 0.16859701 0.10843092]
[0.49120998 0.63699596 0.79885208 0.24122891 0.73505877]


array([[0.98089887, 0.8351129 , 0.67325678, 1.23087995, 0.73705009],
       [1.85805582, 1.71226984, 1.55041372, 2.10803689, 1.61420703],
       [3.09616256, 2.95037659, 2.78852047, 3.34614364, 2.85231378],
       [5.44009314, 5.29430717, 5.13245105, 5.69007422, 5.19624436],
       [8.73125201, 8.58546604, 8.42360992, 8.98123309, 8.48740322]])

48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [77]:
int_types = [int8, int16, int32, int64, uint8, uint16, uint32,uint64]
for i in int_types:
    info = np.iinfo(i)
    print(f'{i.__name__}: min: {info.min}, max: {info.max}')
    
float = [float16, float32, float64]
for f in float:
    info = np.finfo(f)
    print(f'{f.__name__}: min: {info.min}, max: {info.max}')

int8: min: -128, max: 127
int16: min: -32768, max: 32767
int32: min: -2147483648, max: 2147483647
int64: min: -9223372036854775808, max: 9223372036854775807
uint8: min: 0, max: 255
uint16: min: 0, max: 65535
uint32: min: 0, max: 4294967295
uint64: min: 0, max: 18446744073709551615
float16: min: -65504.0, max: 65504.0
float32: min: -3.4028234663852886e+38, max: 3.4028234663852886e+38
float64: min: -1.7976931348623157e+308, max: 1.7976931348623157e+308


49. How to print all the values of an array? (★★☆)

In [86]:
x = np.arange(10)

for i in x:
    print(f'{i}')

0
1
2
3
4
5
6
7
8
9


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [92]:
x = np.random.rand(10)*100
scalar = 42

index = np.abs(x-scalar).argmin()
print(x)
print(scalar)
print(index)

[12.81233038 78.11676505 97.74431641 31.4788589  52.25448105 70.50403819
 25.04582139 60.40320477 80.46590401 30.76454827]
42
4



51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [95]:
dtype = [('position', [('x', float16), ('y', float16)]), ('color', [('r', int), ('g', int), ('b', int)])]
arr = np.zeros(3, dtype=dtype)
arr['position']['x'] = [1.0, 2.0, 3.0]
arr['position']['y'] = [4.0, 5.0, 6.0]
arr['color']['r'] = [255, 128, 0]
arr['color']['g'] = [0, 255, 128]
arr['color']['b'] = [128, 0, 255]

print(arr)


[((1., 4.), (255,   0, 128)) ((2., 5.), (128, 255,   0))
 ((3., 6.), (  0, 128, 255))]
