1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
print(np.show_config())

1.23.5
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
Supported SIMD extensions i

3. Create a null vector of size 10 (★☆☆)

In [9]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [12]:
print(x.size)

10


5. How to get the documentation of the numpy add function from the command line?

In [13]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
x = np.zeros(10)
x[4] = 1 
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
x = np.flip(x)
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
x = np.matrix([[0,1,2], [3,4,5], [6,7,8]])
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
x = np.array([1,2,0,0,4,0])
np.where(x == 0)[0]

array([2, 3, 5])

11. Create a 3x3 identity matrix (★☆☆)

In [28]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
x = np.random.random((3,3,3))
x

array([[[0.61142367, 0.06564817, 0.50772502],
        [0.425998  , 0.81502132, 0.92848528],
        [0.7936402 , 0.08242476, 0.71443872]],

       [[0.7604757 , 0.09268343, 0.76721741],
        [0.78921626, 0.68069777, 0.20933696],
        [0.25716784, 0.45209221, 0.99604358]],

       [[0.86992168, 0.10247123, 0.60332738],
        [0.34613451, 0.06063756, 0.21126365],
        [0.51871395, 0.45888206, 0.11260058]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
x = np.random.random((10,10))
print(x.max())
print(x.min())

0.9998037398806727
0.002943698161203434


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [36]:
x = np.random.random(30)
print(x.mean())

0.5326791407333195
