1. Import the numpy package under the name np (★☆☆)

In [140]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [141]:
print(np.__version__)
print(np.show_config())

1.23.5
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
Supported SIMD extensions i

3. Create a null vector of size 10 (★☆☆)

In [142]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [143]:
print(x.size)

10


5. How to get the documentation of the numpy add function from the command line?

In [144]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [145]:
x = np.zeros(10)
x[4] = 1 
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [146]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [147]:
x = np.flip(x)
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [148]:
x = np.matrix([[0,1,2], [3,4,5], [6,7,8]])
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [149]:
x = np.array([1,2,0,0,4,0])
np.where(x == 0)[0]

array([2, 3, 5])

11. Create a 3x3 identity matrix (★☆☆)

In [150]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [151]:
x = np.random.random((3,3,3))
x

array([[[0.50652163, 0.91662187, 0.93362638],
        [0.19396662, 0.80322254, 0.98953494],
        [0.50488691, 0.13274895, 0.39599606]],

       [[0.61342423, 0.95823028, 0.98352188],
        [0.80752458, 0.28191623, 0.88944576],
        [0.79270313, 0.54692629, 0.21335963]],

       [[0.92330084, 0.76407056, 0.56167327],
        [0.72022707, 0.53486816, 0.87663061],
        [0.01303258, 0.00124491, 0.90617159]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [152]:
x = np.random.random((10,10))
print(x.max())
print(x.min())

0.9871448613775433
0.015857719006728832


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [153]:
x = np.random.random(30)
print(x.mean())

0.5855415103117934


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [154]:
x = np.ones((5,5))
x

x[1:-1, 1:-1] = 0 
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

https://numpy.org/doc/stable/reference/generated/numpy.pad.html

In [155]:
y = np.pad(array=x, pad_width=1)
y

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)

In [156]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

https://numpy.org/doc/stable/reference/generated/numpy.diag.html

In [157]:
x = np.diag([1,2,3,4], k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [158]:
x = np.ones((8,8))
x

x[1::2, ::2] = 0
x[::2, 1::2] = 0
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [159]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [160]:
x = np.array([[1,0], [0,1]])
x = np.tile(x,(4,4))
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a 5x5 random matrix (★☆☆)

In [161]:
x = np.random.rand(5,5)
x = (x-x.min() / (x.max() - x.min()))
x

array([[-2.47109097e-04,  3.01640550e-01,  5.45537639e-01,
         4.08775114e-01,  7.40566279e-01],
       [ 9.76805843e-01,  5.04408556e-02,  1.12912191e-01,
         5.59538308e-01,  1.70787124e-02],
       [ 3.10109182e-01,  8.61110701e-01,  1.55735440e-01,
         1.93502638e-01,  7.31498198e-01],
       [ 2.21049067e-01,  2.73638270e-01,  6.98955401e-01,
         6.58688109e-01,  1.41673903e-02],
       [ 2.27800943e-01,  1.86613478e-01,  4.51619085e-01,
         8.27423130e-01,  5.22598130e-01]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [162]:
color = np.dtype([('r', np.uint8),
                   ('g', np.uint8),
                   ('b', np.uint8),
                   ('a', np.uint8)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [163]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)
z = np.matmul(x,y)
z

array([[1.16942874, 0.87995115],
       [1.36185397, 0.88154474],
       [1.45069888, 1.03580724],
       [0.80644883, 0.4498643 ],
       [0.6626408 , 0.36921341]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [164]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
y = x[3:8]*-1
x[3:8] = y
x

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

In [165]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

x[(x >= 3) & (x <= 8)] *= -1
x

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

26. What is the output of the following script? (★☆☆)

https://stackoverflow.com/questions/57567658/why-sum-behaves-differently-after-i-import-numpy

In [166]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [167]:
Z = np.arange(10)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


28. What are the result of the following expressions? (★☆☆)

In [168]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_4624/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_4624/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([0.])

29. How to round away from zero a float array ? (★☆☆)

https://numpy.org/doc/2.2/reference/generated/numpy.floor.html

https://numpy.org/doc/2.2/reference/generated/numpy.ceil.html

In [169]:
#Floor
x = np.linspace(0,10, 15)
print(x)
x = np.floor(x)
print(x)
print('\n')
#Ceil
y = np.linspace(0,10,15)
print(y)
y = np.ceil(y)
print(y)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[ 0.  0.  1.  2.  2.  3.  4.  5.  5.  6.  7.  7.  8.  9. 10.]


[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[ 0.  1.  2.  3.  3.  4.  5.  5.  6.  7.  8.  8.  9. 10. 10.]


30. How to find common values between two arrays? (★☆☆)

In [170]:
x = np.array([1,2,3,4,5,6,7])
y = np.array([2,4,6,8,9])

print(np.intersect1d(x,y))

#For more than two arrayes use
from functools import reduce
z = np.array([3,6,9])
reduce(np.intersect1d,(x,y,z))

[2 4 6]


array([6])

31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [171]:
#np.seterr(all='ignore')

32. Is the following expressions true? (★☆☆)

In [172]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_4624/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [173]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(f'Yesterda was {yesterday}, today is {today}, tomrrow will be {tomorrow}')

Yesterda was 2025-06-14, today is 2025-06-15, tomrrow will be 2025-06-16


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

https://numpy.org/doc/2.2/reference/arrays.datetime.html

In [174]:
x = np.arange('2016-07-01', '2016-07-31', dtype = 'datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [175]:
x = np.ones(3) * 2
y = np.ones(3) * 3

x /= -2
y += x
y *= x
print(y)

[-2. -2. -2.]


36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [176]:
x = np.random.uniform(0,10,6)

print(x)

#1
print(x.astype(uint8))

#2
print(np.floor(x))

#3
print(np.trunc(x))

#4
print(np.round(x))

[0.43875643 0.55543981 0.63762413 4.81093954 7.20654177 2.17281525]
[0 0 0 4 7 2]
[0. 0. 0. 4. 7. 2.]
[0. 0. 0. 4. 7. 2.]
[0. 1. 1. 5. 7. 2.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [177]:
x = np.array([0,1,2,3,4])
y = np.tile(x,(5,1))
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [178]:
def gen_array():
    for _ in range(10):
        yield np.random.randint(0, 100)
        
x = np.fromiter(gen_array(), dtype='int')
x


array([79, 87, 79, 39, 73, 22, 97, 82, 93, 16])

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [179]:
x = np.linspace(0,1,12)
x = x[1:11]
x.size

10

40. Create a random vector of size 10 and sort it (★★☆)

In [180]:
np.sort(x)
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

41. How to sum a small array faster than np.sum? (★★☆)

In [183]:
x = np.arange(10)
x

#Sum
print(np.sum(x))

#Alternative
print(np.add.reduce(x))

45
45


42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
x = np.arange(10)
y = np.arange(10)

x == y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

43. Make an array immutable (read-only) (★★☆)

In [ ]:
x = np.array(10)
x.flags.writeable = False
#x[0] = 1

ValueError: assignment destination is read-only

In [ ]:
param_grid = {
    #'n_estimators': [100, 200],
    #'learning_rate': [0.01, 0.1],
    #'max_depth': [3, 5],
    #'subsample': [0.8, 1.0]
}

#gbm = GradientBoostingClassifier(random_state=42)

#grid_search = GridSearchCV(estimator=gbm, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
#grid_search.fit(X_train, y_train)

#print("Best parameters found: ", grid_search.best_params_)