1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.23.5
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/anaconda3/envs/DataScience/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/DataScience/include']
Supported SIMD extensions i

3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [5]:
print(x.size)

10


5. How to get the documentation of the numpy add function from the command line?

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4] = 1 
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x = np.flip(x)
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
x = np.matrix([[0,1,2], [3,4,5], [6,7,8]])
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
x = np.array([1,2,0,0,4,0])
np.where(x == 0)[0]

array([2, 3, 5])

11. Create a 3x3 identity matrix (★☆☆)

In [12]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
x = np.random.random((3,3,3))
x

array([[[0.906859  , 0.44368953, 0.60324059],
        [0.64497163, 0.82445204, 0.68157556],
        [0.4764622 , 0.74699222, 0.19556757]],

       [[0.43257936, 0.44181287, 0.62555938],
        [0.2093348 , 0.21015556, 0.29464864],
        [0.81023253, 0.52234322, 0.64340279]],

       [[0.49510383, 0.23780915, 0.12754993],
        [0.41994736, 0.90630327, 0.77483495],
        [0.09423788, 0.87837672, 0.08652042]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
x = np.random.random((10,10))
print(x.max())
print(x.min())

0.9802857890893971
0.002651819459646765


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
x = np.random.random(30)
print(x.mean())

0.3745281985288856


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
x = np.ones((5,5))
x

x[1:-1, 1:-1] = 0 
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

https://numpy.org/doc/stable/reference/generated/numpy.pad.html

In [17]:
y = np.pad(array=x, pad_width=1)
y

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)

In [18]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

https://numpy.org/doc/stable/reference/generated/numpy.diag.html

In [19]:
x = np.diag([1,2,3,4], k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
x = np.ones((8,8))
x

x[1::2, ::2] = 0
x[::2, 1::2] = 0
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
x = np.array([[1,0], [0,1]])
x = np.tile(x,(4,4))
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
x = np.random.rand(5,5)
x = (x-x.min() / (x.max() - x.min()))
x

array([[ 9.16062066e-01,  6.92270282e-02,  7.61712109e-01,
         7.30208630e-01,  7.54600025e-01],
       [ 9.67271245e-01,  2.38552796e-01, -5.97146925e-06,
         6.04617766e-01,  3.73930951e-01],
       [ 3.13395847e-01,  5.59224179e-01,  9.59693557e-01,
         5.49377728e-01,  5.96134703e-01],
       [ 9.37331498e-01,  9.59747641e-01,  2.81791154e-02,
         4.66150068e-01,  2.24522185e-01],
       [ 7.92989442e-01,  6.30301406e-01,  3.46081645e-01,
         2.22191544e-01,  8.72152999e-02]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([('r', np.uint8),
                   ('g', np.uint8),
                   ('b', np.uint8),
                   ('a', np.uint8)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)
z = np.matmul(x,y)
z

array([[0.49987458, 0.4182636 ],
       [0.40691974, 0.62881403],
       [0.23767776, 0.585209  ],
       [0.11096646, 0.48481851],
       [0.22293248, 0.43166374]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
y = x[3:8]*-1
x[3:8] = y
x

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

In [27]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

x[(x >= 3) & (x <= 8)] *= -1
x

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

26. What is the output of the following script? (★☆☆)

https://stackoverflow.com/questions/57567658/why-sum-behaves-differently-after-i-import-numpy

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [29]:
Z = np.arange(10)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


28. What are the result of the following expressions? (★☆☆)

In [30]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_1296/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_1296/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([0.])

29. How to round away from zero a float array ? (★☆☆)

https://numpy.org/doc/2.2/reference/generated/numpy.floor.html

https://numpy.org/doc/2.2/reference/generated/numpy.ceil.html

In [31]:
#Floor
x = np.linspace(0,10, 15)
print(x)
x = np.floor(x)
print(x)
print('\n')
#Ceil
y = np.linspace(0,10,15)
print(y)
y = np.ceil(y)
print(y)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[ 0.  0.  1.  2.  2.  3.  4.  5.  5.  6.  7.  7.  8.  9. 10.]


[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[ 0.  1.  2.  3.  3.  4.  5.  5.  6.  7.  8.  8.  9. 10. 10.]


30. How to find common values between two arrays? (★☆☆)

In [41]:
x = np.array([1,2,3,4,5,6,7])
y = np.array([2,4,6,8,9])

print(np.intersect1d(x,y))

#For more than two arrayes use
from functools import reduce
z = np.array([3,6,9])
reduce(np.intersect1d,(x,y,z))

[2 4 6]


array([6])

31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [42]:
#np.seterr(all='ignore')

32. Is the following expressions true? (★☆☆)

In [46]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_1296/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(f'Yesterda was {yesterday}, today is {today}, tomrrow will be {tomorrow}')

Yesterda was 2025-06-10, today is 2025-06-11, tomrrow will be 2025-06-12


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

https://numpy.org/doc/2.2/reference/arrays.datetime.html

In [53]:
x = np.arange('2016-07-01', '2016-07-31', dtype = 'datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')